-- ============================================================
-- SUPPLY CHAIN & INVENTORY ANALYTICS
-- 01 - CREATE TABLE
-- PostgreSQL
-- ============================================================
-- Purpose:
-- Create the main table used by the project.
--
-- The table structure matches the RAW CSV dataset.
-- Derived / analytical columns will be created later
-- using PostgreSQL.
-- ============================================================


-- ============================================================
-- 1. DROP EXISTING TABLE
-- ============================================================

DROP TABLE IF EXISTS supply_chain_inventory;


-- ============================================================
-- 2. CREATE MAIN TABLE
-- ============================================================

CREATE TABLE supply_chain_inventory (

    -- --------------------------------------------------------
    -- PostgreSQL Record Identifier
    -- --------------------------------------------------------
    -- This column is generated by PostgreSQL.
    -- It is NOT present in the raw CSV.

    record_id BIGSERIAL PRIMARY KEY,


    -- --------------------------------------------------------
    -- Date
    -- --------------------------------------------------------

    date DATE NOT NULL,


    -- --------------------------------------------------------
    -- Business Dimensions
    -- --------------------------------------------------------

    sku_id VARCHAR(50) NOT NULL,

    warehouse_id VARCHAR(50) NOT NULL,

    supplier_id VARCHAR(50) NOT NULL,

    region VARCHAR(100),


    -- --------------------------------------------------------
    -- Demand & Inventory
    -- --------------------------------------------------------

    units_sold INTEGER,

    inventory_level INTEGER,


    -- --------------------------------------------------------
    -- Replenishment
    -- --------------------------------------------------------

    supplier_lead_time_days INTEGER,

    reorder_point INTEGER,

    order_quantity INTEGER,


    -- --------------------------------------------------------
    -- Financial Inputs
    -- --------------------------------------------------------

    unit_cost NUMERIC(12,2),

    unit_price NUMERIC(12,2),


    -- --------------------------------------------------------
    -- Operational Flags
    -- --------------------------------------------------------

    promotion_flag INTEGER,

    stockout_flag INTEGER,


    -- --------------------------------------------------------
    -- Demand Forecast
    -- --------------------------------------------------------

    demand_forecast NUMERIC(12,2)

);


-- ============================================================
-- 3. BASIC TABLE VERIFICATION
-- ============================================================

SELECT *
FROM supply_chain_inventory
LIMIT 10;


-- ============================================================
-- 4. CHECK TABLE STRUCTURE
-- ============================================================

SELECT
    ordinal_position,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_name = 'supply_chain_inventory'
ORDER BY ordinal_position;


-- ============================================================
-- 5. EXPECTED COLUMN COUNT
-- ============================================================

SELECT
    COUNT(*) AS total_columns
FROM information_schema.columns
WHERE table_name = 'supply_chain_inventory';